Feature pfdtzf
eugeneslab-taiga/foxtrip.common.logger pull request #2
Opened 2021-11-23 13:06 UTC by K3130

Lets get started)

2021-11-23 14:36 UTC, tagiltsev-evgenii requested changes

2021-11-23 14:36 UTC, tagiltsev-evgenii commented on Tc2log_Logger.cpp
> +}
Если при начальной инициализации был выбран метод "Только запись в файл", то переключение на метод "Только запись в консоль" работать не станет

2021-11-23 14:36 UTC, tagiltsev-evgenii commented on Tc2log_Logger.cpp
> +        m_DataBase = QSqlDatabase::addDatabase("QSQLITE");
Дайте имя соединению. Например: loggerConnection. И не забудьте указать receiveMessage поменять

2021-11-23 14:36 UTC, tagiltsev-evgenii commented on Tc2log_Logger.cpp
> +        db.setDatabaseName(QDir::currentPath() + "/logs/log.db");
У нас есть путь в m_dir. По ТЗ не надо было делать эту функцию с static квалификатором.

2021-11-23 14:36 UTC, tagiltsev-evgenii commented on Tc2log_Logger.cpp
> +                              + query.value(4).toString();
Если вы явно в запросе SELECT не указываете порядок полей для вывода, то вот такое выражение может выдать вам поля не в том порядке которое мы бы хотели.

2021-11-24 20:18 UTC, tagiltsev-evgenii commented
Task linked: [CU-pfdtzf Fc2log_Logger](https://app.clickup.com/t/pfdtzf)

2021-11-24 20:22 UTC, tagiltsev-evgenii commented
Task linked: [CU-pfdtzf Fc2log_Logger](https://app.clickup.com/t/pfdtzf)

2021-11-25 05:50 UTC, K3130 commented on Tc2log_Logger.cpp
> +}
Хмм... Проверил, работает.

2021-11-25 14:45 UTC, tagiltsev-evgenii requested changes

2021-11-25 14:45 UTC, tagiltsev-evgenii commented on Tc2log_Logger.h
> +    virtual void receiveMessage(QtMsgType aType, const QString& aMessage, int aLineNumber);
virtual void receiveMessage(const QtMsgType aType, const QString& aMessage, const int aLineNumber)

2021-11-25 14:45 UTC, tagiltsev-evgenii commented on Tc2log_Logger.h
> +    QStringList find(QtMsgType aType, const QDateTime& aTimeFrom, const QDateTime& aTimeBefore);
QStringList find(const QtMsgType aType, const QDateTime& aTimeFrom, const QDateTime& aTimeBefore);
 
 Проверьте еще раз все функции и исправьте где это необходимо

2021-11-25 14:45 UTC, tagiltsev-evgenii commented on Tc2log_Logger.h
> +    void setLevel(QtMsgType aType);
void setLevel(const QtMsgType aType);

2021-11-25 14:45 UTC, tagiltsev-evgenii commented on Tc2log_Logger.cpp
> +        }
Используйте ту базу данных, которая уже открыта

2021-11-25 14:45 UTC, tagiltsev-evgenii commented on Tc2log_Logger.cpp
> +        query.bindValue(":Date", QDateTime::currentDateTime().toString("yyyy-MM-dd hh:mm"));
Забыл сказать: время по UTC лучше записывать, что бы не привязываться к конкретному региону

2021-11-25 14:45 UTC, tagiltsev-evgenii commented on Tc2log_Logger.cpp
> +        QTextStream(stdout) << levelString(aType) + " " << QDateTime::currentDateTime().toString("yyyy-MM-dd hh:mm ")
Время по UTC

2021-11-25 14:45 UTC, tagiltsev-evgenii commented on Tc2log_Logger.h
> +    QString outputDir();
QString outputDir() const;

Т.к. мы получаем путь из m_Dir, то скорее всего можно даже сделать так:

const QString& outputDir() const;

2021-11-25 14:45 UTC, tagiltsev-evgenii commented on Tc2log_Logger.h
> +    OutputMethod outputMethod();
OutputMethod outputMethod() const;

2021-11-26 07:11 UTC, tagiltsev-evgenii approved these changes

2021-11-26 07:11 UTC, merged